name = "AutoGIS"
uuid = "ec2bce09-24df-4203-8502-12daad671fd3"
authors = ["Ed Fawcett-Taylor <edwardpaultaylor@gmail.com>"]
version = "0.1.0"

[deps]
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
